### ISSUE TITLE
Make update error

### ISSUE THREAD

**Issue by Invictaz** [juan518munoz/PicoSwitch-WirelessGamepadAdapter#10]
The make file has a fatal error.
Maybe this has something to do with a dependency or the missing Pico SDK?

![image](https://github.com/juan518munoz/PicoSwitch-WirelessGamepadAdapter/assets/20338545/b9c6533b-0c99-4a65-be61-940fc5bc904f)

**Comment by juan518munoz** [comment]
Can't replicate on my side, does `git submodule update --init --recursive` generate the same outcome?

**Comment by Invictaz** [comment]
I did my compiling on an Ubuntu livedvd so I cannot test now.
