### ISSUE TITLE
Is the adapter cannot remember registered gamepads?

### ISSUE THREAD

**Issue by MadDaimond** [juan518munoz/PicoSwitch-WirelessGamepadAdapter#4]
Each time, when I connect the Pico Board to USB it goes to "scanning for the gamepad" mode and I need to sync gamepads each time I am plug it in. Is it normal behaviour? Can the Pico adapter remember the already synchronized gamepad?

**Comment by juan518munoz** [comment]
Yes, it should pick up previous connected gamepads without needing to resync them.
