### ISSUE TITLE
XBOX One controller button mapping is backwards.

### ISSUE THREAD

**Issue by DaPiMan** [juan518munoz/PicoSwitch-WirelessGamepadAdapter#6]
XBOX One controller button mapping is backwards.

A is B and B is A, X is Y and Y is X.

Apart from this it's not very intuitive on when/how to get a controller to connect to the device. Is it possible to enable the LED to "flash" or indicate when it's connecting a device? I am thinking of installing a blue LED on the GPIO and having it enabled for connections.

**Comment by Invictaz** [comment]
There is no remap in the Switch menu possible

**Comment by juan518munoz** [comment]
Sorry for the delayed response.

> XBOX One controller button mapping is backwards.
This can be easily changed inside [`pico_switch_platform_init`](https://github.com/juan518munoz/PicoSwitch-WirelessGamepadAdapter/blob/main/src/pico_switch_platform.c#L157-L161)

> Is it possible to enable the LED to "flash" or indicate when it's connecting a device?
Yes, the led can be toggled on/of with this line
```c
cyw43_arch_gpio_put(CYW43_WL_GPIO_LED_PIN, 1);
```
The legacy binary of the program has led flashing that indicates status, I removed it while debugging the pico crashing and forgot to re-add it.

**Comment by Invictaz** [comment]
I hope to compile it some day. But I'm waiting for the DS5 fix first to avond to use the legacy version. Or to make a separate DS5 version. 

@juan518munoz

**Comment by juan518munoz** [comment]
Legacy and current version are funtionally the same, the only difference is in it's codebase.
- Legacy uses bluepad32 as a directory and is heavely modified.
- Current version uses bluepad32 as a [submodule](https://gist.github.com/gitaarik/8735255) so updating it is easier.

**Comment by Invictaz** [comment]
@DaPiMan I compiled a version with the buttons in correct order

[PicoSwitchWGA-xbox.zip](https://github.com/juan518munoz/PicoSwitch-WirelessGamepadAdapter/files/14673062/PicoSwitchWGA-xbox.zip)

@juan518munoz there are no instructions on how to compile legacy version sadly

**Comment by juan518munoz** [comment]
Legacy version is based of [this commit](https://github.com/juan518munoz/PicoSwitch-WirelessGamepadAdapter/tree/a27fa88ad9fe27f9910a4c372b8bd03b403d1ae1), you can `git reset` into it so you can compile it.

**Comment by Invictaz** [comment]
Apparently my compiled firmware does not work. I removed the link and will try to recompile it.

**Comment by Invictaz** [comment]
I recompiled the button switch. Tested with my Xbox Elite 2 controller and I played over 50 mins fine. 

[PicoSwitchWGA-xboxremap.zip](https://github.com/juan518munoz/PicoSwitch-WirelessGamepadAdapter/files/14737162/PicoSwitchWGA-xboxremap.zip)

Dualshock 4 indeed has a problem, you can change the color on the controller and there are timeouts or connection problems. 
I will try with the reset option and recompile. Maybe the Dualshock 4 problem is the same as the Dualshock 5 (Dualsense)?

**Comment by Invictaz** [comment]
The legacy version must be compiled with ./build.sh
