### ISSUE TITLE
PS3 output

### ISSUE THREAD

**Issue by Invictaz** [juan518munoz/PicoSwitch-WirelessGamepadAdapter#7]
Would it be possible to have Playstation 3 output since it is also unencrypted just like the Switch?

See
https://rb4.app/

It has UF2 firmware but not for all the sticks I guess.

**Comment by juan518munoz** [comment]
If the PS3 supports USB gamepads and is unencrypted like you say, it's totally possible.

**Comment by Invictaz** [comment]
@juan518munoz See

https://github.com/wiredopposite/OGX-Mini/commit/ff48a177507ac1a87fbedc14944ee9b1d46dc7c9#diff-bc9b0f539bbb46807dcddf40572e494a6539994e2473f11778b12a46723e49e9R96

For an example on how to implement the HID driver for the PS3.

**Comment by juan518munoz** [comment]
Does not seem difficult at all, but I don't own a PS3 to test whether what I do works or not, so I'll leave porting to this platform open for somebody else to do.

**Comment by Invictaz** [comment]
@juan518munoz I do have an PS3 so I can test for you

**Comment by juan518munoz** [comment]
This would be cumbersome to debug and would take more time, I'll leave PS3 implementation open to someone else to do, and ask another user to verify the PR if it's ever requested.

**Comment by Invictaz** [comment]
@juan518munoz You have the RPCS3 emulator so no need for anything to debug.
